export const dummyData = {
  location: {
    name: "London",
    region: "City of London, Greater London",
    country: "United Kingdom",
    lat: 51.52,
    lon: -0.11,
    tz_id: "Europe/London",
    localtime_epoch: 1620395306,
    localtime: "2021-05-07 14:48",
  },
  current: {
    last_updated_epoch: 1620395100,
    last_updated: "2021-05-07 14:45",
    temp_c: 15.0,
    temp_f: 59.0,
    is_day: 1,
    condition: {
      text: "Sunny",
      icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
      code: 1000,
    },
    wind_mph: 13.6,
    wind_kph: 22.0,
    wind_degree: 250,
    wind_dir: "WSW",
    pressure_mb: 1017.0,
    pressure_in: 30.5,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 29,
    cloud: 0,
    feelslike_c: 14.3,
    feelslike_f: 57.7,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 4.0,
    gust_mph: 9.4,
    gust_kph: 15.1,
  },
  forecast: {
    forecastday: [
      {
        date: "2021-05-07",
        date_epoch: 1620345600,
        day: {
          maxtemp_c: 13.6,
          maxtemp_f: 56.5,
          mintemp_c: 4.6,
          mintemp_f: 40.3,
          avgtemp_c: 8.8,
          avgtemp_f: 47.9,
          maxwind_mph: 9.8,
          maxwind_kph: 15.8,
          totalprecip_mm: 0.8,
          totalprecip_in: 0.03,
          avgvis_km: 9.9,
          avgvis_miles: 6.0,
          avghumidity: 65.0,
          daily_will_it_rain: 1,
          daily_chance_of_rain: "88",
          daily_will_it_snow: 0,
          daily_chance_of_snow: "0",
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 5.0,
        },
        astro: {
          sunrise: "05:22 AM",
          sunset: "08:34 PM",
          moonrise: "04:25 AM",
          moonset: "03:51 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "14",
        },
        hour: [
          {
            time_epoch: 1620342000,
            time: "2021-05-07 00:00",
            temp_c: 5.4,
            temp_f: 41.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 285,
            wind_dir: "WNW",
            pressure_mb: 1010.0,
            pressure_in: 30.3,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 73,
            cloud: 38,
            feelslike_c: 2.1,
            feelslike_f: 35.8,
            windchill_c: 2.1,
            windchill_f: 35.8,
            heatindex_c: 5.4,
            heatindex_f: 41.7,
            dewpoint_c: 1.0,
            dewpoint_f: 33.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.3,
            gust_kph: 23.0,
            uv: 1.0,
          },
          {
            time_epoch: 1620345600,
            time: "2021-05-07 01:00",
            temp_c: 5.1,
            temp_f: 41.2,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 285,
            wind_dir: "WNW",
            pressure_mb: 1011.0,
            pressure_in: 30.3,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 76,
            cloud: 26,
            feelslike_c: 1.9,
            feelslike_f: 35.4,
            windchill_c: 1.9,
            windchill_f: 35.4,
            heatindex_c: 5.1,
            heatindex_f: 41.2,
            dewpoint_c: 1.3,
            dewpoint_f: 34.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.8,
            gust_kph: 20.5,
            uv: 1.0,
          },
          {
            time_epoch: 1620349200,
            time: "2021-05-07 02:00",
            temp_c: 4.9,
            temp_f: 40.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.7,
            wind_kph: 14.0,
            wind_degree: 285,
            wind_dir: "WNW",
            pressure_mb: 1012.0,
            pressure_in: 30.3,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 79,
            cloud: 15,
            feelslike_c: 1.8,
            feelslike_f: 35.2,
            windchill_c: 1.8,
            windchill_f: 35.2,
            heatindex_c: 4.9,
            heatindex_f: 40.8,
            dewpoint_c: 1.5,
            dewpoint_f: 34.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.4,
            gust_kph: 18.4,
            uv: 1.0,
          },
          {
            time_epoch: 1620352800,
            time: "2021-05-07 03:00",
            temp_c: 4.6,
            temp_f: 40.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.1,
            wind_kph: 13.0,
            wind_degree: 286,
            wind_dir: "WNW",
            pressure_mb: 1012.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 82,
            cloud: 4,
            feelslike_c: 1.6,
            feelslike_f: 34.9,
            windchill_c: 1.6,
            windchill_f: 34.9,
            heatindex_c: 4.6,
            heatindex_f: 40.3,
            dewpoint_c: 1.8,
            dewpoint_f: 35.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 1.0,
          },
          {
            time_epoch: 1620356400,
            time: "2021-05-07 04:00",
            temp_c: 4.7,
            temp_f: 40.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 290,
            wind_dir: "WNW",
            pressure_mb: 1013.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 81,
            cloud: 11,
            feelslike_c: 1.8,
            feelslike_f: 35.2,
            windchill_c: 1.8,
            windchill_f: 35.2,
            heatindex_c: 4.7,
            heatindex_f: 40.5,
            dewpoint_c: 1.7,
            dewpoint_f: 35.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 1.0,
          },
          {
            time_epoch: 1620360000,
            time: "2021-05-07 05:00",
            temp_c: 4.8,
            temp_f: 40.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 295,
            wind_dir: "WNW",
            pressure_mb: 1014.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 79,
            cloud: 18,
            feelslike_c: 2.1,
            feelslike_f: 35.8,
            windchill_c: 2.1,
            windchill_f: 35.8,
            heatindex_c: 4.8,
            heatindex_f: 40.6,
            dewpoint_c: 1.5,
            dewpoint_f: 34.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1.0,
          },
          {
            time_epoch: 1620363600,
            time: "2021-05-07 06:00",
            temp_c: 4.9,
            temp_f: 40.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 299,
            wind_dir: "WNW",
            pressure_mb: 1014.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 78,
            cloud: 25,
            feelslike_c: 2.3,
            feelslike_f: 36.1,
            windchill_c: 2.3,
            windchill_f: 36.1,
            heatindex_c: 4.9,
            heatindex_f: 40.8,
            dewpoint_c: 1.4,
            dewpoint_f: 34.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 2.0,
          },
          {
            time_epoch: 1620367200,
            time: "2021-05-07 07:00",
            temp_c: 6.8,
            temp_f: 44.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 302,
            wind_dir: "WNW",
            pressure_mb: 1015.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 70,
            cloud: 19,
            feelslike_c: 4.5,
            feelslike_f: 40.1,
            windchill_c: 4.5,
            windchill_f: 40.1,
            heatindex_c: 6.8,
            heatindex_f: 44.2,
            dewpoint_c: 1.3,
            dewpoint_f: 34.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.7,
            gust_kph: 14.0,
            uv: 3.0,
          },
          {
            time_epoch: 1620370800,
            time: "2021-05-07 08:00",
            temp_c: 8.6,
            temp_f: 47.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 305,
            wind_dir: "NW",
            pressure_mb: 1015.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 13,
            feelslike_c: 6.6,
            feelslike_f: 43.9,
            windchill_c: 6.6,
            windchill_f: 43.9,
            heatindex_c: 8.6,
            heatindex_f: 47.5,
            dewpoint_c: 1.3,
            dewpoint_f: 34.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.7,
            gust_kph: 14.0,
            uv: 3.0,
          },
          {
            time_epoch: 1620374400,
            time: "2021-05-07 09:00",
            temp_c: 10.5,
            temp_f: 50.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 307,
            wind_dir: "NW",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 7,
            feelslike_c: 8.8,
            feelslike_f: 47.8,
            windchill_c: 8.8,
            windchill_f: 47.8,
            heatindex_c: 10.5,
            heatindex_f: 50.9,
            dewpoint_c: 1.2,
            dewpoint_f: 34.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 4.0,
          },
          {
            time_epoch: 1620378000,
            time: "2021-05-07 10:00",
            temp_c: 11.3,
            temp_f: 52.3,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 8.1,
            wind_kph: 13.0,
            wind_degree: 300,
            wind_dir: "WNW",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 48,
            cloud: 33,
            feelslike_c: 9.8,
            feelslike_f: 49.6,
            windchill_c: 9.8,
            windchill_f: 49.6,
            heatindex_c: 11.3,
            heatindex_f: 52.3,
            dewpoint_c: 0.5,
            dewpoint_f: 32.9,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 3.0,
          },
          {
            time_epoch: 1620381600,
            time: "2021-05-07 11:00",
            temp_c: 12.2,
            temp_f: 54.0,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 8.1,
            wind_kph: 13.0,
            wind_degree: 294,
            wind_dir: "WNW",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 43,
            cloud: 59,
            feelslike_c: 10.8,
            feelslike_f: 51.4,
            windchill_c: 10.8,
            windchill_f: 51.4,
            heatindex_c: 12.2,
            heatindex_f: 54.0,
            dewpoint_c: -0.3,
            dewpoint_f: 31.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 4.0,
          },
          {
            time_epoch: 1620385200,
            time: "2021-05-07 12:00",
            temp_c: 13.0,
            temp_f: 55.4,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 287,
            wind_dir: "WNW",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 38,
            cloud: 84,
            feelslike_c: 11.8,
            feelslike_f: 53.2,
            windchill_c: 11.8,
            windchill_f: 53.2,
            heatindex_c: 13.0,
            heatindex_f: 55.4,
            dewpoint_c: -1.0,
            dewpoint_f: 30.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.6,
            gust_kph: 15.5,
            uv: 3.0,
          },
          {
            time_epoch: 1620388800,
            time: "2021-05-07 13:00",
            temp_c: 13.2,
            temp_f: 55.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 8.1,
            wind_kph: 13.0,
            wind_degree: 280,
            wind_dir: "W",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 38,
            cloud: 74,
            feelslike_c: 12.1,
            feelslike_f: 53.8,
            windchill_c: 12.1,
            windchill_f: 53.8,
            heatindex_c: 13.2,
            heatindex_f: 55.8,
            dewpoint_c: -0.9,
            dewpoint_f: 30.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 4.0,
          },
          {
            time_epoch: 1620392400,
            time: "2021-05-07 14:00",
            temp_c: 13.4,
            temp_f: 56.1,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 8.1,
            wind_kph: 13.0,
            wind_degree: 272,
            wind_dir: "W",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 37,
            cloud: 64,
            feelslike_c: 12.3,
            feelslike_f: 54.1,
            windchill_c: 12.3,
            windchill_f: 54.1,
            heatindex_c: 13.4,
            heatindex_f: 56.1,
            dewpoint_c: -0.9,
            dewpoint_f: 30.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 3.0,
          },
          {
            time_epoch: 1620396000,
            time: "2021-05-07 15:00",
            temp_c: 13.6,
            temp_f: 56.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 265,
            wind_dir: "W",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 37,
            cloud: 54,
            feelslike_c: 12.6,
            feelslike_f: 54.7,
            windchill_c: 12.6,
            windchill_f: 54.7,
            heatindex_c: 13.6,
            heatindex_f: 56.5,
            dewpoint_c: -0.8,
            dewpoint_f: 30.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 4.0,
          },
          {
            time_epoch: 1620399600,
            time: "2021-05-07 16:00",
            temp_c: 12.6,
            temp_f: 54.7,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 255,
            wind_dir: "WSW",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 48,
            cloud: 69,
            feelslike_c: 11.4,
            feelslike_f: 52.5,
            windchill_c: 11.4,
            windchill_f: 52.5,
            heatindex_c: 12.6,
            heatindex_f: 54.7,
            dewpoint_c: 1.3,
            dewpoint_f: 34.3,
            will_it_rain: 0,
            chance_of_rain: "29",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 3.0,
          },
          {
            time_epoch: 1620403200,
            time: "2021-05-07 17:00",
            temp_c: 11.5,
            temp_f: 52.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 244,
            wind_dir: "WSW",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 60,
            cloud: 85,
            feelslike_c: 10.2,
            feelslike_f: 50.4,
            windchill_c: 10.2,
            windchill_f: 50.4,
            heatindex_c: 11.5,
            heatindex_f: 52.7,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: "59",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 4.0,
          },
          {
            time_epoch: 1620406800,
            time: "2021-05-07 18:00",
            temp_c: 10.5,
            temp_f: 50.9,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 233,
            wind_dir: "SW",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.5,
            precip_in: 0.02,
            humidity: 72,
            cloud: 100,
            feelslike_c: 9.0,
            feelslike_f: 48.2,
            windchill_c: 9.0,
            windchill_f: 48.2,
            heatindex_c: 10.5,
            heatindex_f: 50.9,
            dewpoint_c: 5.6,
            dewpoint_f: 42.1,
            will_it_rain: 1,
            chance_of_rain: "88",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 3.0,
          },
          {
            time_epoch: 1620410400,
            time: "2021-05-07 19:00",
            temp_c: 9.7,
            temp_f: 49.5,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 224,
            wind_dir: "SW",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 76,
            cloud: 91,
            feelslike_c: 8.2,
            feelslike_f: 46.8,
            windchill_c: 8.2,
            windchill_f: 46.8,
            heatindex_c: 9.7,
            heatindex_f: 49.5,
            dewpoint_c: 5.6,
            dewpoint_f: 42.1,
            will_it_rain: 1,
            chance_of_rain: "81",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.7,
            vis_miles: 6.0,
            gust_mph: 8.7,
            gust_kph: 14.0,
            uv: 2.0,
          },
          {
            time_epoch: 1620414000,
            time: "2021-05-07 20:00",
            temp_c: 8.8,
            temp_f: 47.8,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 215,
            wind_dir: "SW",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 81,
            cloud: 81,
            feelslike_c: 7.5,
            feelslike_f: 45.5,
            windchill_c: 7.5,
            windchill_f: 45.5,
            heatindex_c: 8.8,
            heatindex_f: 47.8,
            dewpoint_c: 5.7,
            dewpoint_f: 42.3,
            will_it_rain: 1,
            chance_of_rain: "74",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.3,
            vis_miles: 5.0,
            gust_mph: 8.1,
            gust_kph: 13.0,
            uv: 2.0,
          },
          {
            time_epoch: 1620417600,
            time: "2021-05-07 21:00",
            temp_c: 8.0,
            temp_f: 46.4,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 205,
            wind_dir: "SSW",
            pressure_mb: 1017.0,
            pressure_in: 30.5,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 86,
            cloud: 72,
            feelslike_c: 6.7,
            feelslike_f: 44.1,
            windchill_c: 6.7,
            windchill_f: 44.1,
            heatindex_c: 8.0,
            heatindex_f: 46.4,
            dewpoint_c: 5.7,
            dewpoint_f: 42.3,
            will_it_rain: 0,
            chance_of_rain: "67",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 1.0,
          },
          {
            time_epoch: 1620421200,
            time: "2021-05-07 22:00",
            temp_c: 7.4,
            temp_f: 45.3,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 194,
            wind_dir: "SSW",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 85,
            cloud: 81,
            feelslike_c: 6.1,
            feelslike_f: 43.0,
            windchill_c: 6.1,
            windchill_f: 43.0,
            heatindex_c: 7.4,
            heatindex_f: 45.3,
            dewpoint_c: 5.0,
            dewpoint_f: 41.0,
            will_it_rain: 1,
            chance_of_rain: "74",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.3,
            vis_miles: 5.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 1.0,
          },
          {
            time_epoch: 1620424800,
            time: "2021-05-07 23:00",
            temp_c: 6.7,
            temp_f: 44.1,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 184,
            wind_dir: "S",
            pressure_mb: 1016.0,
            pressure_in: 30.5,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 84,
            cloud: 91,
            feelslike_c: 5.4,
            feelslike_f: 41.7,
            windchill_c: 5.4,
            windchill_f: 41.7,
            heatindex_c: 6.7,
            heatindex_f: 44.1,
            dewpoint_c: 4.2,
            dewpoint_f: 39.6,
            will_it_rain: 1,
            chance_of_rain: "82",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.7,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 1.0,
          },
        ],
      },
      {
        date: "2021-05-08",
        date_epoch: 1620432000,
        day: {
          maxtemp_c: 13.2,
          maxtemp_f: 55.8,
          mintemp_c: 6.0,
          mintemp_f: 42.8,
          avgtemp_c: 8.8,
          avgtemp_f: 47.8,
          maxwind_mph: 17.7,
          maxwind_kph: 28.4,
          totalprecip_mm: 17.6,
          totalprecip_in: 0.69,
          avgvis_km: 8.8,
          avgvis_miles: 5.0,
          avghumidity: 87.0,
          daily_will_it_rain: 1,
          daily_chance_of_rain: "90",
          daily_will_it_snow: 0,
          daily_chance_of_snow: "0",
          condition: {
            text: "Moderate rain",
            icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
            code: 1189,
          },
          uv: 2.0,
        },
        astro: {
          sunrise: "05:20 AM",
          sunset: "08:35 PM",
          moonrise: "04:39 AM",
          moonset: "05:00 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "7",
        },
        hour: [
          {
            time_epoch: 1620428400,
            time: "2021-05-08 00:00",
            temp_c: 6.1,
            temp_f: 43.0,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 173,
            wind_dir: "S",
            pressure_mb: 1015.0,
            pressure_in: 30.5,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 83,
            cloud: 100,
            feelslike_c: 4.8,
            feelslike_f: 40.6,
            windchill_c: 4.8,
            windchill_f: 40.6,
            heatindex_c: 6.1,
            heatindex_f: 43.0,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 1,
            chance_of_rain: "89",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.9,
            gust_kph: 11.2,
            uv: 1.0,
          },
          {
            time_epoch: 1620432000,
            time: "2021-05-08 01:00",
            temp_c: 6.1,
            temp_f: 43.0,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 162,
            wind_dir: "SSE",
            pressure_mb: 1014.0,
            pressure_in: 30.4,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 80,
            cloud: 100,
            feelslike_c: 4.4,
            feelslike_f: 39.9,
            windchill_c: 4.4,
            windchill_f: 39.9,
            heatindex_c: 6.1,
            heatindex_f: 43.0,
            dewpoint_c: 2.8,
            dewpoint_f: 37.0,
            will_it_rain: 0,
            chance_of_rain: "59",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 1.0,
          },
          {
            time_epoch: 1620435600,
            time: "2021-05-08 02:00",
            temp_c: 6.0,
            temp_f: 42.8,
            is_day: 0,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 151,
            wind_dir: "SSE",
            pressure_mb: 1014.0,
            pressure_in: 30.4,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 76,
            cloud: 100,
            feelslike_c: 4.0,
            feelslike_f: 39.2,
            windchill_c: 4.0,
            windchill_f: 39.2,
            heatindex_c: 6.0,
            heatindex_f: 42.8,
            dewpoint_c: 2.0,
            dewpoint_f: 35.6,
            will_it_rain: 0,
            chance_of_rain: "30",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 1.0,
          },
          {
            time_epoch: 1620439200,
            time: "2021-05-08 03:00",
            temp_c: 6.0,
            temp_f: 42.8,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 140,
            wind_dir: "SE",
            pressure_mb: 1013.0,
            pressure_in: 30.4,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 100,
            feelslike_c: 3.6,
            feelslike_f: 38.5,
            windchill_c: 3.6,
            windchill_f: 38.5,
            heatindex_c: 6.0,
            heatindex_f: 42.8,
            dewpoint_c: 1.3,
            dewpoint_f: 34.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.9,
            gust_kph: 19.1,
            uv: 1.0,
          },
          {
            time_epoch: 1620442800,
            time: "2021-05-08 04:00",
            temp_c: 6.3,
            temp_f: 43.3,
            is_day: 0,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
              code: 1183,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 140,
            wind_dir: "SE",
            pressure_mb: 1012.0,
            pressure_in: 30.3,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 79,
            cloud: 100,
            feelslike_c: 3.6,
            feelslike_f: 38.5,
            windchill_c: 3.6,
            windchill_f: 38.5,
            heatindex_c: 6.3,
            heatindex_f: 43.3,
            dewpoint_c: 2.8,
            dewpoint_f: 37.0,
            will_it_rain: 0,
            chance_of_rain: "30",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.7,
            vis_miles: 6.0,
            gust_mph: 13.9,
            gust_kph: 22.3,
            uv: 1.0,
          },
          {
            time_epoch: 1620446400,
            time: "2021-05-08 05:00",
            temp_c: 6.6,
            temp_f: 43.9,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 140,
            wind_dir: "SE",
            pressure_mb: 1010.0,
            pressure_in: 30.3,
            precip_mm: 0.7,
            precip_in: 0.03,
            humidity: 85,
            cloud: 100,
            feelslike_c: 3.6,
            feelslike_f: 38.5,
            windchill_c: 3.6,
            windchill_f: 38.5,
            heatindex_c: 6.6,
            heatindex_f: 43.9,
            dewpoint_c: 4.2,
            dewpoint_f: 39.6,
            will_it_rain: 0,
            chance_of_rain: "60",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.3,
            vis_miles: 5.0,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 1.0,
          },
          {
            time_epoch: 1620450000,
            time: "2021-05-08 06:00",
            temp_c: 6.9,
            temp_f: 44.4,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 140,
            wind_dir: "SE",
            pressure_mb: 1009.0,
            pressure_in: 30.3,
            precip_mm: 1.0,
            precip_in: 0.04,
            humidity: 92,
            cloud: 100,
            feelslike_c: 3.6,
            feelslike_f: 38.5,
            windchill_c: 3.6,
            windchill_f: 38.5,
            heatindex_c: 6.9,
            heatindex_f: 44.4,
            dewpoint_c: 5.7,
            dewpoint_f: 42.3,
            will_it_rain: 1,
            chance_of_rain: "90",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 17.9,
            gust_kph: 28.8,
            uv: 2.0,
          },
          {
            time_epoch: 1620453600,
            time: "2021-05-08 07:00",
            temp_c: 7.4,
            temp_f: 45.3,
            is_day: 1,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            wind_mph: 12.5,
            wind_kph: 20.2,
            wind_degree: 146,
            wind_dir: "SSE",
            pressure_mb: 1008.0,
            pressure_in: 30.2,
            precip_mm: 2.1,
            precip_in: 0.08,
            humidity: 94,
            cloud: 100,
            feelslike_c: 4.0,
            feelslike_f: 39.2,
            windchill_c: 4.0,
            windchill_f: 39.2,
            heatindex_c: 7.4,
            heatindex_f: 45.3,
            dewpoint_c: 6.4,
            dewpoint_f: 43.5,
            will_it_rain: 1,
            chance_of_rain: "89",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 8.3,
            vis_miles: 5.0,
            gust_mph: 19.7,
            gust_kph: 31.7,
            uv: 2.0,
          },
          {
            time_epoch: 1620457200,
            time: "2021-05-08 08:00",
            temp_c: 7.8,
            temp_f: 46.0,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 152,
            wind_dir: "SSE",
            pressure_mb: 1006.0,
            pressure_in: 30.2,
            precip_mm: 3.1,
            precip_in: 0.12,
            humidity: 95,
            cloud: 100,
            feelslike_c: 4.4,
            feelslike_f: 39.9,
            windchill_c: 4.4,
            windchill_f: 39.9,
            heatindex_c: 7.8,
            heatindex_f: 46.0,
            dewpoint_c: 7.1,
            dewpoint_f: 44.8,
            will_it_rain: 1,
            chance_of_rain: "89",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 7.7,
            vis_miles: 4.0,
            gust_mph: 21.3,
            gust_kph: 34.2,
            uv: 2.0,
          },
          {
            time_epoch: 1620460800,
            time: "2021-05-08 09:00",
            temp_c: 8.3,
            temp_f: 46.9,
            is_day: 1,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            wind_mph: 15.0,
            wind_kph: 24.1,
            wind_degree: 158,
            wind_dir: "SSE",
            pressure_mb: 1005.0,
            pressure_in: 30.1,
            precip_mm: 4.2,
            precip_in: 0.17,
            humidity: 97,
            cloud: 100,
            feelslike_c: 4.8,
            feelslike_f: 40.6,
            windchill_c: 4.8,
            windchill_f: 40.6,
            heatindex_c: 8.3,
            heatindex_f: 46.9,
            dewpoint_c: 7.8,
            dewpoint_f: 46.0,
            will_it_rain: 1,
            chance_of_rain: "89",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 7.0,
            vis_miles: 4.0,
            gust_mph: 23.0,
            gust_kph: 37.1,
            uv: 2.0,
          },
          {
            time_epoch: 1620464400,
            time: "2021-05-08 10:00",
            temp_c: 9.2,
            temp_f: 48.6,
            is_day: 1,
            condition: {
              text: "Heavy rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/308.png",
              code: 1195,
            },
            wind_mph: 15.9,
            wind_kph: 25.6,
            wind_degree: 170,
            wind_dir: "S",
            pressure_mb: 1004.0,
            pressure_in: 30.1,
            precip_mm: 6.1,
            precip_in: 0.24,
            humidity: 96,
            cloud: 100,
            feelslike_c: 5.9,
            feelslike_f: 42.6,
            windchill_c: 5.9,
            windchill_f: 42.6,
            heatindex_c: 9.2,
            heatindex_f: 48.6,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 1,
            chance_of_rain: "84",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 6.3,
            vis_miles: 3.0,
            gust_mph: 24.8,
            gust_kph: 40.0,
            uv: 2.0,
          },
          {
            time_epoch: 1620468000,
            time: "2021-05-08 11:00",
            temp_c: 10.2,
            temp_f: 50.4,
            is_day: 1,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            wind_mph: 16.8,
            wind_kph: 27.0,
            wind_degree: 182,
            wind_dir: "S",
            pressure_mb: 1003.0,
            pressure_in: 30.1,
            precip_mm: 8.1,
            precip_in: 0.32,
            humidity: 96,
            cloud: 100,
            feelslike_c: 7.0,
            feelslike_f: 44.6,
            windchill_c: 7.0,
            windchill_f: 44.6,
            heatindex_c: 10.2,
            heatindex_f: 50.4,
            dewpoint_c: 9.6,
            dewpoint_f: 49.3,
            will_it_rain: 1,
            chance_of_rain: "80",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 5.7,
            vis_miles: 3.0,
            gust_mph: 26.4,
            gust_kph: 42.5,
            uv: 3.0,
          },
          {
            time_epoch: 1620471600,
            time: "2021-05-08 12:00",
            temp_c: 11.1,
            temp_f: 52.0,
            is_day: 1,
            condition: {
              text: "Heavy rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/308.png",
              code: 1195,
            },
            wind_mph: 17.7,
            wind_kph: 28.4,
            wind_degree: 194,
            wind_dir: "SSW",
            pressure_mb: 1002.0,
            pressure_in: 30.1,
            precip_mm: 10.0,
            precip_in: 0.39,
            humidity: 96,
            cloud: 100,
            feelslike_c: 8.1,
            feelslike_f: 46.6,
            windchill_c: 8.1,
            windchill_f: 46.6,
            heatindex_c: 11.1,
            heatindex_f: 52.0,
            dewpoint_c: 10.5,
            dewpoint_f: 50.9,
            will_it_rain: 1,
            chance_of_rain: "75",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 5.0,
            vis_miles: 3.0,
            gust_mph: 28.2,
            gust_kph: 45.4,
            uv: 3.0,
          },
          {
            time_epoch: 1620475200,
            time: "2021-05-08 13:00",
            temp_c: 11.8,
            temp_f: 53.2,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 17.4,
            wind_kph: 28.1,
            wind_degree: 201,
            wind_dir: "SSW",
            pressure_mb: 1002.0,
            pressure_in: 30.1,
            precip_mm: 7.4,
            precip_in: 0.29,
            humidity: 95,
            cloud: 100,
            feelslike_c: 9.0,
            feelslike_f: 48.2,
            windchill_c: 9.0,
            windchill_f: 48.2,
            heatindex_c: 11.8,
            heatindex_f: 53.2,
            dewpoint_c: 11.0,
            dewpoint_f: 51.8,
            will_it_rain: 1,
            chance_of_rain: "74",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 6.3,
            vis_miles: 3.0,
            gust_mph: 28.2,
            gust_kph: 45.4,
            uv: 3.0,
          },
          {
            time_epoch: 1620478800,
            time: "2021-05-08 14:00",
            temp_c: 12.5,
            temp_f: 54.5,
            is_day: 1,
            condition: {
              text: "Heavy rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/308.png",
              code: 1195,
            },
            wind_mph: 17.0,
            wind_kph: 27.4,
            wind_degree: 208,
            wind_dir: "SSW",
            pressure_mb: 1002.0,
            pressure_in: 30.1,
            precip_mm: 4.7,
            precip_in: 0.19,
            humidity: 94,
            cloud: 100,
            feelslike_c: 10.0,
            feelslike_f: 50.0,
            windchill_c: 10.0,
            windchill_f: 50.0,
            heatindex_c: 12.5,
            heatindex_f: 54.5,
            dewpoint_c: 11.5,
            dewpoint_f: 52.7,
            will_it_rain: 1,
            chance_of_rain: "72",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 7.7,
            vis_miles: 4.0,
            gust_mph: 28.0,
            gust_kph: 45.0,
            uv: 3.0,
          },
          {
            time_epoch: 1620482400,
            time: "2021-05-08 15:00",
            temp_c: 13.2,
            temp_f: 55.8,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 16.8,
            wind_kph: 27.0,
            wind_degree: 215,
            wind_dir: "SW",
            pressure_mb: 1001.0,
            pressure_in: 30.0,
            precip_mm: 2.1,
            precip_in: 0.08,
            humidity: 92,
            cloud: 100,
            feelslike_c: 10.9,
            feelslike_f: 51.6,
            windchill_c: 10.9,
            windchill_f: 51.6,
            heatindex_c: 13.2,
            heatindex_f: 55.8,
            dewpoint_c: 12.0,
            dewpoint_f: 53.6,
            will_it_rain: 1,
            chance_of_rain: "71",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 28.0,
            gust_kph: 45.0,
            uv: 3.0,
          },
          {
            time_epoch: 1620486000,
            time: "2021-05-08 16:00",
            temp_c: 12.5,
            temp_f: 54.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 15.9,
            wind_kph: 25.6,
            wind_degree: 215,
            wind_dir: "SW",
            pressure_mb: 1001.0,
            pressure_in: 30.0,
            precip_mm: 1.4,
            precip_in: 0.06,
            humidity: 90,
            cloud: 87,
            feelslike_c: 11.0,
            feelslike_f: 51.8,
            windchill_c: 11.0,
            windchill_f: 51.8,
            heatindex_c: 13.9,
            heatindex_f: 57.0,
            dewpoint_c: 12.0,
            dewpoint_f: 53.6,
            will_it_rain: 0,
            chance_of_rain: "47",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.3,
            vis_miles: 5.0,
            gust_mph: 26.4,
            gust_kph: 42.5,
            uv: 4.0,
          },
          {
            time_epoch: 1620489600,
            time: "2021-05-08 17:00",
            temp_c: 11.9,
            temp_f: 53.4,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 15.2,
            wind_kph: 24.5,
            wind_degree: 215,
            wind_dir: "SW",
            pressure_mb: 1001.0,
            pressure_in: 30.0,
            precip_mm: 0.7,
            precip_in: 0.03,
            humidity: 87,
            cloud: 74,
            feelslike_c: 11.1,
            feelslike_f: 52.0,
            windchill_c: 11.1,
            windchill_f: 52.0,
            heatindex_c: 14.5,
            heatindex_f: 58.1,
            dewpoint_c: 12.1,
            dewpoint_f: 53.8,
            will_it_rain: 0,
            chance_of_rain: "24",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.7,
            vis_miles: 6.0,
            gust_mph: 24.8,
            gust_kph: 40.0,
            uv: 3.0,
          },
          {
            time_epoch: 1620493200,
            time: "2021-05-08 18:00",
            temp_c: 11.2,
            temp_f: 52.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 14.3,
            wind_kph: 23.0,
            wind_degree: 215,
            wind_dir: "SW",
            pressure_mb: 1001.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 84,
            cloud: 62,
            feelslike_c: 11.2,
            feelslike_f: 52.2,
            windchill_c: 11.2,
            windchill_f: 52.2,
            heatindex_c: 15.2,
            heatindex_f: 59.4,
            dewpoint_c: 12.1,
            dewpoint_f: 53.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.3,
            gust_kph: 37.4,
            uv: 4.0,
          },
          {
            time_epoch: 1620496800,
            time: "2021-05-08 19:00",
            temp_c: 9.9,
            temp_f: 49.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 14.1,
            wind_kph: 22.7,
            wind_degree: 212,
            wind_dir: "SSW",
            pressure_mb: 1001.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 83,
            cloud: 45,
            feelslike_c: 9.9,
            feelslike_f: 49.8,
            windchill_c: 9.9,
            windchill_f: 49.8,
            heatindex_c: 13.5,
            heatindex_f: 56.3,
            dewpoint_c: 11.3,
            dewpoint_f: 52.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.3,
            gust_kph: 37.4,
            uv: 3.0,
          },
          {
            time_epoch: 1620500400,
            time: "2021-05-08 20:00",
            temp_c: 8.5,
            temp_f: 47.3,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 13.6,
            wind_kph: 22.0,
            wind_degree: 210,
            wind_dir: "SSW",
            pressure_mb: 1001.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 81,
            cloud: 29,
            feelslike_c: 8.5,
            feelslike_f: 47.3,
            windchill_c: 8.5,
            windchill_f: 47.3,
            heatindex_c: 11.9,
            heatindex_f: 53.4,
            dewpoint_c: 10.6,
            dewpoint_f: 51.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.3,
            gust_kph: 37.4,
            uv: 3.0,
          },
          {
            time_epoch: 1620504000,
            time: "2021-05-08 21:00",
            temp_c: 7.2,
            temp_f: 45.0,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 207,
            wind_dir: "SSW",
            pressure_mb: 1001.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 80,
            cloud: 13,
            feelslike_c: 7.2,
            feelslike_f: 45.0,
            windchill_c: 7.2,
            windchill_f: 45.0,
            heatindex_c: 10.2,
            heatindex_f: 50.4,
            dewpoint_c: 9.8,
            dewpoint_f: 49.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 23.3,
            gust_kph: 37.4,
            uv: 1.0,
          },
          {
            time_epoch: 1620507600,
            time: "2021-05-08 22:00",
            temp_c: 8.9,
            temp_f: 48.0,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 12.8,
            wind_kph: 20.5,
            wind_degree: 202,
            wind_dir: "SSW",
            pressure_mb: 1000.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 81,
            cloud: 10,
            feelslike_c: 8.3,
            feelslike_f: 46.9,
            windchill_c: 8.3,
            windchill_f: 46.9,
            heatindex_c: 10.9,
            heatindex_f: 51.6,
            dewpoint_c: 9.8,
            dewpoint_f: 49.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 21.7,
            gust_kph: 34.9,
            uv: 1.0,
          },
          {
            time_epoch: 1620511200,
            time: "2021-05-08 23:00",
            temp_c: 10.7,
            temp_f: 51.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 12.3,
            wind_kph: 19.8,
            wind_degree: 197,
            wind_dir: "SSW",
            pressure_mb: 1000.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 82,
            cloud: 7,
            feelslike_c: 9.4,
            feelslike_f: 48.9,
            windchill_c: 9.4,
            windchill_f: 48.9,
            heatindex_c: 11.7,
            heatindex_f: 53.1,
            dewpoint_c: 9.7,
            dewpoint_f: 49.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 20.4,
            gust_kph: 32.8,
            uv: 1.0,
          },
        ],
      },
      {
        date: "2021-05-09",
        date_epoch: 1620518400,
        day: {
          maxtemp_c: 18.7,
          maxtemp_f: 65.7,
          mintemp_c: 11.9,
          mintemp_f: 53.4,
          avgtemp_c: 14.7,
          avgtemp_f: 58.4,
          maxwind_mph: 13.9,
          maxwind_kph: 22.3,
          totalprecip_mm: 0.4,
          totalprecip_in: 0.02,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 70.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: "68",
          daily_will_it_snow: 0,
          daily_chance_of_snow: "0",
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 6.0,
        },
        astro: {
          sunrise: "05:18 AM",
          sunset: "08:37 PM",
          moonrise: "04:52 AM",
          moonset: "06:08 PM",
          moon_phase: "New Moon",
          moon_illumination: "0",
        },
        hour: [
          {
            time_epoch: 1620514800,
            time: "2021-05-09 00:00",
            temp_c: 12.4,
            temp_f: 54.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 11.6,
            wind_kph: 18.7,
            wind_degree: 193,
            wind_dir: "SSW",
            pressure_mb: 1000.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 84,
            cloud: 3,
            feelslike_c: 10.5,
            feelslike_f: 50.9,
            windchill_c: 10.5,
            windchill_f: 50.9,
            heatindex_c: 12.4,
            heatindex_f: 54.3,
            dewpoint_c: 9.7,
            dewpoint_f: 49.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.8,
            gust_kph: 30.2,
            uv: 1.0,
          },
          {
            time_epoch: 1620518400,
            time: "2021-05-09 01:00",
            temp_c: 12.2,
            temp_f: 54.0,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 192,
            wind_dir: "SSW",
            pressure_mb: 999.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 83,
            cloud: 9,
            feelslike_c: 10.3,
            feelslike_f: 50.5,
            windchill_c: 10.3,
            windchill_f: 50.5,
            heatindex_c: 12.2,
            heatindex_f: 54.0,
            dewpoint_c: 9.3,
            dewpoint_f: 48.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.8,
            gust_kph: 30.2,
            uv: 1.0,
          },
          {
            time_epoch: 1620522000,
            time: "2021-05-09 02:00",
            temp_c: 12.1,
            temp_f: 53.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 11.0,
            wind_kph: 17.6,
            wind_degree: 192,
            wind_dir: "SSW",
            pressure_mb: 998.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 81,
            cloud: 15,
            feelslike_c: 10.2,
            feelslike_f: 50.4,
            windchill_c: 10.2,
            windchill_f: 50.4,
            heatindex_c: 12.1,
            heatindex_f: 53.8,
            dewpoint_c: 9.0,
            dewpoint_f: 48.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.6,
            gust_kph: 29.9,
            uv: 1.0,
          },
          {
            time_epoch: 1620525600,
            time: "2021-05-09 03:00",
            temp_c: 11.9,
            temp_f: 53.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 191,
            wind_dir: "SSW",
            pressure_mb: 997.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 80,
            cloud: 21,
            feelslike_c: 10.0,
            feelslike_f: 50.0,
            windchill_c: 10.0,
            windchill_f: 50.0,
            heatindex_c: 11.9,
            heatindex_f: 53.4,
            dewpoint_c: 8.6,
            dewpoint_f: 47.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.6,
            gust_kph: 29.9,
            uv: 1.0,
          },
          {
            time_epoch: 1620529200,
            time: "2021-05-09 04:00",
            temp_c: 12.2,
            temp_f: 54.0,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 186,
            wind_dir: "S",
            pressure_mb: 997.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 79,
            cloud: 21,
            feelslike_c: 10.5,
            feelslike_f: 50.9,
            windchill_c: 10.5,
            windchill_f: 50.9,
            heatindex_c: 12.2,
            heatindex_f: 54.0,
            dewpoint_c: 8.6,
            dewpoint_f: 47.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.0,
            gust_kph: 27.4,
            uv: 1.0,
          },
          {
            time_epoch: 1620532800,
            time: "2021-05-09 05:00",
            temp_c: 12.5,
            temp_f: 54.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 181,
            wind_dir: "S",
            pressure_mb: 997.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 78,
            cloud: 22,
            feelslike_c: 10.9,
            feelslike_f: 51.6,
            windchill_c: 10.9,
            windchill_f: 51.6,
            heatindex_c: 12.5,
            heatindex_f: 54.5,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.4,
            gust_kph: 24.8,
            uv: 1.0,
          },
          {
            time_epoch: 1620536400,
            time: "2021-05-09 06:00",
            temp_c: 12.8,
            temp_f: 55.0,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 176,
            wind_dir: "S",
            pressure_mb: 996.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 76,
            cloud: 23,
            feelslike_c: 11.4,
            feelslike_f: 52.5,
            windchill_c: 11.4,
            windchill_f: 52.5,
            heatindex_c: 12.8,
            heatindex_f: 55.0,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.9,
            gust_kph: 22.3,
            uv: 4.0,
          },
          {
            time_epoch: 1620540000,
            time: "2021-05-09 07:00",
            temp_c: 14.3,
            temp_f: 57.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 184,
            wind_dir: "S",
            pressure_mb: 996.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 71,
            cloud: 27,
            feelslike_c: 13.4,
            feelslike_f: 56.1,
            windchill_c: 13.4,
            windchill_f: 56.1,
            heatindex_c: 14.3,
            heatindex_f: 57.7,
            dewpoint_c: 9.1,
            dewpoint_f: 48.4,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.5,
            gust_kph: 23.4,
            uv: 4.0,
          },
          {
            time_epoch: 1620543600,
            time: "2021-05-09 08:00",
            temp_c: 15.9,
            temp_f: 60.6,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 12.3,
            wind_kph: 19.8,
            wind_degree: 192,
            wind_dir: "SSW",
            pressure_mb: 996.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 32,
            feelslike_c: 15.4,
            feelslike_f: 59.7,
            windchill_c: 15.4,
            windchill_f: 59.7,
            heatindex_c: 15.9,
            heatindex_f: 60.6,
            dewpoint_c: 9.4,
            dewpoint_f: 48.9,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.4,
            gust_kph: 24.8,
            uv: 5.0,
          },
          {
            time_epoch: 1620547200,
            time: "2021-05-09 09:00",
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 200,
            wind_dir: "SSW",
            pressure_mb: 996.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 36,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            windchill_c: 17.4,
            windchill_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            dewpoint_c: 9.8,
            dewpoint_f: 49.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.1,
            gust_kph: 25.9,
            uv: 5.0,
          },
          {
            time_epoch: 1620550800,
            time: "2021-05-09 10:00",
            temp_c: 17.8,
            temp_f: 64.0,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 13.9,
            wind_kph: 22.3,
            wind_degree: 198,
            wind_dir: "SSW",
            pressure_mb: 996.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 59,
            cloud: 28,
            feelslike_c: 17.8,
            feelslike_f: 64.0,
            windchill_c: 17.8,
            windchill_f: 64.0,
            heatindex_c: 17.8,
            heatindex_f: 64.0,
            dewpoint_c: 9.7,
            dewpoint_f: 49.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 5.0,
          },
          {
            time_epoch: 1620554400,
            time: "2021-05-09 11:00",
            temp_c: 18.3,
            temp_f: 64.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 13.6,
            wind_kph: 22.0,
            wind_degree: 196,
            wind_dir: "SSW",
            pressure_mb: 995.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 57,
            cloud: 20,
            feelslike_c: 18.3,
            feelslike_f: 64.9,
            windchill_c: 18.3,
            windchill_f: 64.9,
            heatindex_c: 18.3,
            heatindex_f: 64.9,
            dewpoint_c: 9.6,
            dewpoint_f: 49.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 5.0,
          },
          {
            time_epoch: 1620558000,
            time: "2021-05-09 12:00",
            temp_c: 18.7,
            temp_f: 65.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 13.6,
            wind_kph: 22.0,
            wind_degree: 194,
            wind_dir: "SSW",
            pressure_mb: 995.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 55,
            cloud: 12,
            feelslike_c: 18.7,
            feelslike_f: 65.7,
            windchill_c: 18.7,
            windchill_f: 65.7,
            heatindex_c: 18.7,
            heatindex_f: 65.7,
            dewpoint_c: 9.5,
            dewpoint_f: 49.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.7,
            gust_kph: 25.2,
            uv: 5.0,
          },
          {
            time_epoch: 1620561600,
            time: "2021-05-09 13:00",
            temp_c: 18.3,
            temp_f: 64.9,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 204,
            wind_dir: "SSW",
            pressure_mb: 995.0,
            pressure_in: 29.8,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 59,
            cloud: 28,
            feelslike_c: 18.3,
            feelslike_f: 64.9,
            windchill_c: 18.3,
            windchill_f: 64.9,
            heatindex_c: 18.3,
            heatindex_f: 64.9,
            dewpoint_c: 10.2,
            dewpoint_f: 50.4,
            will_it_rain: 0,
            chance_of_rain: "23",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.2,
            gust_kph: 24.5,
            uv: 4.0,
          },
          {
            time_epoch: 1620565200,
            time: "2021-05-09 14:00",
            temp_c: 17.9,
            temp_f: 64.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 12.5,
            wind_kph: 20.2,
            wind_degree: 215,
            wind_dir: "SW",
            pressure_mb: 995.0,
            pressure_in: 29.8,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 64,
            cloud: 44,
            feelslike_c: 17.9,
            feelslike_f: 64.2,
            windchill_c: 17.9,
            windchill_f: 64.2,
            heatindex_c: 17.9,
            heatindex_f: 64.2,
            dewpoint_c: 10.8,
            dewpoint_f: 51.4,
            will_it_rain: 0,
            chance_of_rain: "45",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.8,
            gust_kph: 23.8,
            uv: 5.0,
          },
          {
            time_epoch: 1620568800,
            time: "2021-05-09 15:00",
            temp_c: 17.5,
            temp_f: 63.5,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 11.9,
            wind_kph: 19.1,
            wind_degree: 225,
            wind_dir: "SW",
            pressure_mb: 995.0,
            pressure_in: 29.8,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 68,
            cloud: 60,
            feelslike_c: 17.5,
            feelslike_f: 63.5,
            windchill_c: 17.5,
            windchill_f: 63.5,
            heatindex_c: 17.5,
            heatindex_f: 63.5,
            dewpoint_c: 11.5,
            dewpoint_f: 52.7,
            will_it_rain: 0,
            chance_of_rain: "68",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.3,
            gust_kph: 23.0,
            uv: 4.0,
          },
          {
            time_epoch: 1620572400,
            time: "2021-05-09 16:00",
            temp_c: 16.5,
            temp_f: 61.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 11.2,
            wind_kph: 18.0,
            wind_degree: 224,
            wind_dir: "SW",
            pressure_mb: 995.0,
            pressure_in: 29.8,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 66,
            cloud: 56,
            feelslike_c: 16.2,
            feelslike_f: 61.2,
            windchill_c: 16.2,
            windchill_f: 61.2,
            heatindex_c: 16.5,
            heatindex_f: 61.7,
            dewpoint_c: 10.3,
            dewpoint_f: 50.5,
            will_it_rain: 0,
            chance_of_rain: "45",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6,
            uv: 5.0,
          },
          {
            time_epoch: 1620576000,
            time: "2021-05-09 17:00",
            temp_c: 15.6,
            temp_f: 60.1,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 222,
            wind_dir: "SW",
            pressure_mb: 995.0,
            pressure_in: 29.8,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 65,
            cloud: 53,
            feelslike_c: 14.8,
            feelslike_f: 58.6,
            windchill_c: 14.8,
            windchill_f: 58.6,
            heatindex_c: 15.6,
            heatindex_f: 60.1,
            dewpoint_c: 9.0,
            dewpoint_f: 48.2,
            will_it_rain: 0,
            chance_of_rain: "23",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.8,
            gust_kph: 20.5,
            uv: 4.0,
          },
          {
            time_epoch: 1620579600,
            time: "2021-05-09 18:00",
            temp_c: 14.6,
            temp_f: 58.3,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 220,
            wind_dir: "SW",
            pressure_mb: 995.0,
            pressure_in: 29.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 49,
            feelslike_c: 13.5,
            feelslike_f: 56.3,
            windchill_c: 13.5,
            windchill_f: 56.3,
            heatindex_c: 14.6,
            heatindex_f: 58.3,
            dewpoint_c: 7.8,
            dewpoint_f: 46.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.9,
            gust_kph: 19.1,
            uv: 4.0,
          },
          {
            time_epoch: 1620583200,
            time: "2021-05-09 19:00",
            temp_c: 13.7,
            temp_f: 56.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 210,
            wind_dir: "SSW",
            pressure_mb: 995.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 68,
            cloud: 47,
            feelslike_c: 12.3,
            feelslike_f: 54.1,
            windchill_c: 12.3,
            windchill_f: 54.1,
            heatindex_c: 13.7,
            heatindex_f: 56.7,
            dewpoint_c: 7.8,
            dewpoint_f: 46.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6,
            uv: 4.0,
          },
          {
            time_epoch: 1620586800,
            time: "2021-05-09 20:00",
            temp_c: 12.8,
            temp_f: 55.0,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 200,
            wind_dir: "SSW",
            pressure_mb: 996.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 72,
            cloud: 46,
            feelslike_c: 11.2,
            feelslike_f: 52.2,
            windchill_c: 11.2,
            windchill_f: 52.2,
            heatindex_c: 12.8,
            heatindex_f: 55.0,
            dewpoint_c: 7.9,
            dewpoint_f: 46.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.0,
            gust_kph: 24.1,
            uv: 4.0,
          },
          {
            time_epoch: 1620590400,
            time: "2021-05-09 21:00",
            temp_c: 11.9,
            temp_f: 53.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 191,
            wind_dir: "SSW",
            pressure_mb: 996.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 77,
            cloud: 44,
            feelslike_c: 10.0,
            feelslike_f: 50.0,
            windchill_c: 10.0,
            windchill_f: 50.0,
            heatindex_c: 11.9,
            heatindex_f: 53.4,
            dewpoint_c: 7.9,
            dewpoint_f: 46.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.6,
            gust_kph: 26.6,
            uv: 1.0,
          },
          {
            time_epoch: 1620594000,
            time: "2021-05-09 22:00",
            temp_c: 11.7,
            temp_f: 53.1,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 11.6,
            wind_kph: 18.7,
            wind_degree: 193,
            wind_dir: "SSW",
            pressure_mb: 996.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 77,
            cloud: 62,
            feelslike_c: 9.7,
            feelslike_f: 49.5,
            windchill_c: 9.7,
            windchill_f: 49.5,
            heatindex_c: 11.7,
            heatindex_f: 53.1,
            dewpoint_c: 7.9,
            dewpoint_f: 46.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.9,
            gust_kph: 28.8,
            uv: 1.0,
          },
          {
            time_epoch: 1620597600,
            time: "2021-05-09 23:00",
            temp_c: 11.6,
            temp_f: 52.9,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 12.8,
            wind_kph: 20.5,
            wind_degree: 195,
            wind_dir: "SSW",
            pressure_mb: 996.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 78,
            cloud: 81,
            feelslike_c: 9.3,
            feelslike_f: 48.7,
            windchill_c: 9.3,
            windchill_f: 48.7,
            heatindex_c: 11.6,
            heatindex_f: 52.9,
            dewpoint_c: 7.9,
            dewpoint_f: 46.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.5,
            gust_kph: 31.3,
            uv: 1.0,
          },
        ],
      },
    ],
  },
};
